### ISSUE TITLE
NPE : No Git commit id found for String ''

### ISSUE THREAD

**Issue by old-o** [shillner/unleash-scm-provider-git#11]
I am trying to build https://github.com/guppy4j/libraries using Jenkins 2.60.1, Jenkins Maven Unleash Plugin 2.3.0, Maven 3.5, unleash-maven-plugin 2.6.0, unleash-scm-provider-git 2.1.0.

I saw the closed issue #9 but I still get that same exception. I tried the Additional Behaviours - Wipe out repository & force clone, but that didn't change anything.

Here is the log snippet:

```
[INFO] 22:28:35,683  Checking remote SCM repository for changes. Initial revision was 933be5ab26f398924ee68cd0106ac50ed623c14d
[INFO] 22:28:35,683  Tagging local and remote SCM repositories.
[INFO] 22:28:35,741  Git - Searching for Git tag '0.0.8'
[INFO] 22:28:36,400  Git - Tagging local repository with '0.0.8'
[INFO] 22:28:36,401  Git - Committing local changes.
[INFO] 22:28:36,792  Git - Commit finished successfully. New revision is: 26f00cf92d3f2eb8c2a5d337b052b673b71e6d05
[INFO] 22:28:39,041  Git - Tag creation finished successfully. New revision is: 
[INFO] 22:28:39,041  Detecting all release artifacts that have been produced during the release build for later installation and deployment.
[INFO] 22:28:39,071  Preparing project modules for next development cycle.
[INFO] 22:28:39,344  Git - Committing local changes.
[INFO] 22:28:39,460  Git - Pushing local changes to remote repository.
[INFO] 22:28:39,462  Git - Updating local repository with remote changes.
[ERROR] An exception was caught while processing the workflow step with id 'setDevVersion'.
com.itemis.maven.plugins.unleash.scm.ScmException: No Git commit id found for String ''.
	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.update(ScmProviderGit.java:472)
	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.push(ScmProviderGit.java:372)
	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.commit(ScmProviderGit.java:336)
	at com.itemis.maven.plugins.unleash.util.DevVersionUtil.commitChanges(DevVersionUtil.java:100)
	at com.itemis.maven.plugins.unleash.steps.actions.SetNextDevVersion.execute(SetNextDevVersion.java:87)
	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep(WorkflowExecutor.java:157)
	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute(WorkflowExecutor.java:119)
	at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute(AbstractCDIMojo.java:209)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.jvnet.hudson.maven3.launcher.Maven35Launcher.main(Maven35Launcher.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at jenkins.maven3.agent.Maven35Main.launch(Maven35Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.eclipse.jgit.api.MergeCommand.include(MergeCommand.java:512)
	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.update(ScmProviderGit.java:470)
	... 40 more
[INFO] Rolling back after execution errors - please find the error messages and stack traces above.
[INFO] 22:28:39,828  Rollback of all pom changes necessary for setting of the development version as well as reverting any made SCM commits.
[INFO] 22:28:39,848  Rollback of SCM tag creation and POM modifications due to a processing exception.
[INFO] 22:28:39,849  Git - Searching for Git tag '0.0.8'
[INFO] 22:28:40,032  Git - Deleting Git tag
[INFO] 22:28:40,033  Git - Searching for Git tag '0.0.8'
[INFO] 22:28:42,241  Rollback of artifact-spy-plugin addition to the build configuration.
[INFO] 22:28:42,299  Rollback of release version updating for all project modules

```

**Comment by kenych** [comment]
this only happens when you run from detached head, try to make sure you are in a branch before unleash runs

**Comment by shillner** [comment]
Yes, @kenych is right. Jenkins by default checks out a detached head which is unfortunate for us.
You just have to add the additional behavior `Check out to specific local branch` (can be empty) and Jenkins will check out the default branch which will fix the issue.

**Comment by old-o** [comment]
Thanks guys and sorry for the late response. What you recommended seems to work nicely. I just published an update of my libraries to Maven Central, first time using unleash instead of release plugin. Cool. :)
