### ISSUE TITLE
Doesn't work with Jenkins plugin & SSH credentials

### ISSUE THREAD

**Issue by coudy** [shillner/unleash-scm-provider-git#8]
I'm trying to provide a username+key into the Jenkins plugin via Jenkins' credentials and it seems to be silently ignored. Using SSH agent isn't practical for me because I'm using a different deploy key for each github project.

Happy to provide more details but looks like this simply isn't implemented. Can you confirm?

**Comment by shillner** [comment]
It is implemented in the Jenkins plugin ([UnleashMavenBuildWrapper#updateCommandWithScmCredentials](https://github.com/jenkinsci/unleash-plugin/blob/master/src/main/java/com/itemis/jenkins/plugins/unleash/UnleashMavenBuildWrapper.java)):

```java
private Map<String, String> updateCommandWithScmCredentials(AbstractBuild build, StringBuilder command) {
    String scmUsername = null;
    String scmPassword = null;
    String scmSshPassphrase = null;
    if (StringUtils.isNotBlank(this.credentialsId)) {
      StandardUsernameCredentials credentials = CredentialsProvider.findCredentialById(this.credentialsId,
          StandardUsernameCredentials.class, build, URIRequirementBuilder.create().build());
      if (credentials instanceof StandardUsernamePasswordCredentials) {
        StandardUsernamePasswordCredentials c = (StandardUsernamePasswordCredentials) credentials;
        scmUsername = c.getUsername();
        scmPassword = c.getPassword().getPlainText();
      } else if (credentials instanceof SSHUserPrivateKey) {
        SSHUserPrivateKey c = (SSHUserPrivateKey) credentials;
        Secret passphrase = c.getPassphrase();
        scmSshPassphrase = passphrase != null ? passphrase.getPlainText() : null;
      }
    }

    final Map<String, String> scmEnv = Maps.newHashMap();
    if (scmUsername != null) {
      command.append(" -Dunleash.scmUsernameEnvVar=" + ENV_VAR_SCM_USERNAME);
      scmEnv.put(ENV_VAR_SCM_USERNAME, scmUsername);
    }
    if (scmPassword != null) {
      command.append(" -Dunleash.scmPasswordEnvVar=" + ENV_VAR_SCM_PASSWORD);
      scmEnv.put(ENV_VAR_SCM_PASSWORD, scmPassword);
    }
    if (scmSshPassphrase != null) {
      command.append(" -Dunleash.scmSshPassphraseEnvVar=" + ENV_VAR_SCM_SSH_PASSPHRASE);
      scmEnv.put(ENV_VAR_SCM_SSH_PASSPHRASE, scmSshPassphrase);
    }
    return scmEnv;
}
```

But it may be that this code is buggy since I'm usually using https-based checkout on Jenkins and thus won't recognize errors of this implementation. When I implemented the code I had a setup working with my github account. So maybe there are differences in how to setup the credentials, ... ?!

I'll have a look at this.

**Comment by shillner** [comment]
I've created a Jenkins issue for that: [JENKINS-44050](https://issues.jenkins-ci.org/browse/JENKINS-44050).

Can you post the first lines of the log of your jenkins job? I'd like to have the maven command that is called for the job.

Thanks a lot.

**Comment by coudy** [comment]
SSH Username with private key

**Comment by coudy** [comment]
Cheers, here's more info as requested:

The credential type is 'SSH Username with private key' and the same one's also being used for the main build.

```
15:02:31 Parsing POMs
15:02:31 Established TCP socket on 51906
15:02:31 [lingua-franca] $ /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java -cp /Users/qredo/.jenkins/plugins/maven-plugin/WEB-INF/lib/maven33-agent-1.8.1.jar:/Users/qredo/.jenkins/tools/hudson.tasks.Maven_MavenInstallation/_usr_local_opt_maven_libexec/boot/plexus-classworlds-2.5.2.jar:/Users/qredo/.jenkins/tools/hudson.tasks.Maven_MavenInstallation/_usr_local_opt_maven_libexec/conf/logging jenkins.maven3.agent.Maven33Main /Users/qredo/.jenkins/tools/hudson.tasks.Maven_MavenInstallation/_usr_local_opt_maven_libexec /Users/qredo/.jenkins/war/WEB-INF/lib/remoting-3.7.jar /Users/qredo/.jenkins/plugins/maven-plugin/WEB-INF/lib/maven33-interceptor-1.8.1.jar /Users/qredo/.jenkins/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-commons-1.8.1.jar 51906
15:02:32 <===[JENKINS REMOTING CAPACITY]===>channel started
15:02:33 Executing Maven:  -B -f /Users/qredo/.jenkins/workspace/lingua-franca/pom.xml unleash:perform -Dunleash.tagNamePattern=@{project.version} -Dunleash.scmMessagePrefix=[unleash-maven-plugin] -DenableLogTimestamps=true -Dunleash.versionUpgradeStrategy=DEFAULT -Dunleash.allowLocalReleaseArtifacts=true -Dunleash.commitBeforeTagging=false
```

...then the build runs happily until...

```
15:03:34 [INFO] 15:03:34,990  Removing artifact-spy-plugin from build configuration.
15:03:35 [INFO] 15:03:35,009  Checking remote SCM repository for changes. Initial revision was f21b2f6dd61de1c37c132b23cd5c73f2b4684cd6
15:03:35 [INFO] 15:03:35,009  Tagging local and remote SCM repositories.
15:03:35 [INFO] 15:03:35,028  Git - Searching for Git tag '0.52'
15:03:36 [ERROR] An exception was caught while processing the workflow step with id 'tagScm'.
15:03:36 com.itemis.maven.plugins.unleash.scm.ScmException: An error occurred while querying the remote git repository for tag '0.52'.
15:03:36 	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.hasTag(ScmProviderGit.java:623)
15:03:36 	at com.itemis.maven.plugins.unleash.steps.actions.TagScm.execute(TagScm.java:88)
15:03:36 	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep(WorkflowExecutor.java:157)
15:03:36 	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute(WorkflowExecutor.java:119)
15:03:36 	at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute(AbstractCDIMojo.java:209)
15:03:36 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
15:03:36 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
15:03:36 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
15:03:36 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
15:03:36 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
15:03:36 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
15:03:36 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
15:03:36 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
15:03:36 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
15:03:36 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
15:03:36 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
15:03:36 	at org.jvnet.hudson.maven3.launcher.Maven33Launcher.main(Maven33Launcher.java:129)
15:03:36 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:03:36 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:03:36 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:03:36 	at java.lang.reflect.Method.invoke(Method.java:498)
15:03:36 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
15:03:36 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
15:03:36 	at jenkins.maven3.agent.Maven33Main.launch(Maven33Main.java:176)
15:03:36 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:03:36 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:03:36 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:03:36 	at java.lang.reflect.Method.invoke(Method.java:498)
15:03:36 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
15:03:36 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
15:03:36 	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
15:03:36 	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
15:03:36 	at hudson.remoting.Request$2.run(Request.java:336)
15:03:36 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
15:03:36 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15:03:36 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
15:03:36 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
15:03:36 	at java.lang.Thread.run(Thread.java:748)
15:03:36 Caused by: org.eclipse.jgit.api.errors.TransportException: ssh://git@github.com/qredo/lingua-franca.git: Auth fail
15:03:36 	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:220)
15:03:36 	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:159)
15:03:36 	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.hasTag(ScmProviderGit.java:617)
15:03:36 	... 37 more
15:03:36 Caused by: org.eclipse.jgit.errors.TransportException: ssh://git@github.com/qredo/lingua-franca.git: Auth fail
15:03:36 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
15:03:36 	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
15:03:36 	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:264)
15:03:36 	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:162)
15:03:36 	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:198)
15:03:36 	... 39 more
15:03:36 Caused by: com.jcraft.jsch.JSchException: Auth fail
15:03:36 	at com.jcraft.jsch.Session.connect(Session.java:491)
15:03:36 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
15:03:36 	... 43 more
15:03:36 [INFO] Rolling back after execution errors - please find the error messages and stack traces above.
```

Hope this helps.

**Comment by shillner** [comment]
Will work in 2.1.0! Only compatible with unleash-maven-plugin in version >= 2.6.0

**Comment by coudy** [comment]
This still isn't working for me on unleash 2.6.0 and scm-git 2.1.0.

The updated Jenkins correctly passes in the key (I can echo it as a pre-build step). However, that key isn't offered to the server (lists as unused in GH). I've tried both EC and RSA keys. `ssh-add`ing the key works as expected. What debugging info can I provide to help?

```
00:30:49 Executing Maven:  -B -f /Users/qredo/.jenkins/workspace/lingua-franca/pom.xml unleash:perform -Dunleash.tagNamePattern=@{project.version} -Dunleash.scmMessagePrefix=[unleash-maven-plugin] -DenableLogTimestamps=true -Dunleash.versionUpgradeStrategy=DEFAULT -Dunleash.allowLocalReleaseArtifacts=true -Dunleash.commitBeforeTagging=false -Dunleash.scmSshPrivateKeyEnvVar=UNLEASH_SCM_SSH_PRIVATE_KEY
.
.
.
00:31:51 [ERROR] An exception was caught while processing the workflow step with id 'tagScm'.
00:31:51 com.itemis.maven.plugins.unleash.scm.ScmException: An error occurred while querying the remote git repository for tag '0.52'.
00:31:51 	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.hasTag(ScmProviderGit.java:622)
00:31:51 	at com.itemis.maven.plugins.unleash.steps.actions.TagScm.execute(TagScm.java:88)
00:31:51 	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep(WorkflowExecutor.java:157)
00:31:51 	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute(WorkflowExecutor.java:119)
00:31:51 	at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute(AbstractCDIMojo.java:209)
00:31:51 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
00:31:51 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
00:31:51 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
00:31:51 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
00:31:51 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
00:31:51 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
00:31:51 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
00:31:51 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
00:31:51 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
00:31:51 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
00:31:51 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
00:31:51 	at org.jvnet.hudson.maven3.launcher.Maven33Launcher.main(Maven33Launcher.java:129)
00:31:51 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:31:51 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:31:51 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:31:51 	at java.lang.reflect.Method.invoke(Method.java:498)
00:31:51 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
00:31:51 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
00:31:51 	at jenkins.maven3.agent.Maven33Main.launch(Maven33Main.java:176)
00:31:51 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:31:51 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:31:51 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:31:51 	at java.lang.reflect.Method.invoke(Method.java:498)
00:31:51 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
00:31:51 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
00:31:51 	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
00:31:51 	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
00:31:51 	at hudson.remoting.Request$2.run(Request.java:336)
00:31:51 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
00:31:51 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:31:51 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
00:31:51 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
00:31:51 	at java.lang.Thread.run(Thread.java:748)
00:31:51 Caused by: org.eclipse.jgit.api.errors.TransportException: ssh://git@github.com/qredo/lingua-franca.git: Auth fail
00:31:51 	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:220)
00:31:51 	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:159)
00:31:51 	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.hasTag(ScmProviderGit.java:616)
00:31:51 	... 37 more
00:31:51 Caused by: org.eclipse.jgit.errors.TransportException: ssh://git@github.com/qredo/lingua-franca.git: Auth fail
00:31:51 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
00:31:51 	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
00:31:51 	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:264)
00:31:51 	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:162)
00:31:51 	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:198)
00:31:51 	... 39 more
00:31:51 Caused by: com.jcraft.jsch.JSchException: Auth fail
00:31:51 	at com.jcraft.jsch.Session.connect(Session.java:491)
00:31:51 	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
00:31:51 	... 43 more
00:31:51 [INFO] Rolling back after execution errors - please find the error messages and stack traces above.
00:31:51 [INFO] 00:31:51,917  Rollback of SCM tag creation and POM modifications due to a processing exception.
```

**Comment by coudy** [comment]
OK, I've stepped through the code and found out two problems: 1) The key is ignored unless you specify a passphrase (unlike in Jenkins) 2) Ed25519 keys are not supported. Anyway, I can live with that. Thanks again for the fix.
